window.CLOSET = {
 "meta": {
  "contact": "phildugg@gmail.com"
 },
 "pieces": [
  {
   "id": "j1",
   "name": "Vintage embroidered denim Baguette",
   "brand": "Fendi",
   "category": "Bag",
   "size": "One size",
   "color": "Denim / floral",
   "condition": "Very good",
   "photo": "jas-fringe.jpg",
   "status": "rent",
   "rent_price_cents": 12000,
   "sale_price_cents": null
  },
  {
   "id": "j2",
   "name": "Floral beaded tank",
   "brand": "Planet Riu",
   "category": "Top",
   "size": "XS",
   "color": "White / multi floral",
   "condition": "Excellent",
   "photo": "jas-cny-floral.jpg",
   "status": "rent",
   "rent_price_cents": 2500,
   "sale_price_cents": 8000
  },
  {
   "id": "j3",
   "name": "Pink sequin mini skirt",
   "brand": "Kill System",
   "category": "Bottom",
   "size": "XS",
   "color": "Pale pink",
   "condition": "Excellent",
   "photo": "jas-cny-floral.jpg",
   "status": "sell",
   "rent_price_cents": null,
   "sale_price_cents": 1800,
   "purchase_price_cents": 3000
  },
  {
   "id": "j4",
   "name": "Seafoam sequin halter top",
   "brand": "",
   "category": "Top",
   "size": "XS",
   "color": "Seafoam green",
   "condition": "Very good",
   "photo": "jas-mermaid.jpg",
   "status": "rent",
   "rent_price_cents": 2000,
   "sale_price_cents": null
  },
  {
   "id": "j5",
   "name": "Polka dot halter top",
   "brand": "Fenity",
   "category": "Top",
   "size": "XS",
   "color": "White / black dot",
   "condition": "Excellent",
   "photo": "jas-london-polka.jpg",
   "status": "rent",
   "rent_price_cents": 2000,
   "sale_price_cents": null
  },
  {
   "id": "j8",
   "name": "White satin mini skirt",
   "brand": "Danielle Guizio",
   "category": "Bottom",
   "size": "XS",
   "color": "White",
   "condition": "Excellent",
   "photo": "jas2-dg-skirt.jpg",
   "status": "rent",
   "rent_price_cents": 2000,
   "sale_price_cents": null
  },
  {
   "id": "j10",
   "name": "Silver organza strapless maxi",
   "brand": "",
   "category": "Dress",
   "size": "XS",
   "color": "Silver",
   "condition": "Excellent",
   "photo": "jas2-silver-maxi.jpg",
   "status": "rent",
   "rent_price_cents": 2500,
   "sale_price_cents": null
  },
  {
   "id": "j11",
   "name": "Cream knit polo midi dress",
   "brand": "Sandro",
   "category": "Dress",
   "size": "XS",
   "color": "Cream / navy trim",
   "condition": "Excellent",
   "photo": "jas2-sandro-knit.jpg",
   "status": "rent",
   "rent_price_cents": 4500,
   "sale_price_cents": null
  },
  {
   "id": "j12",
   "name": "Butter yellow slip maxi",
   "brand": "Meshki",
   "category": "Dress",
   "size": "XS",
   "color": "Butter yellow",
   "condition": "Excellent",
   "photo": "jas2-meshki-yellow.jpg",
   "status": "rent",
   "rent_price_cents": 3000,
   "sale_price_cents": null
  },
  {
   "id": "j14",
   "name": "Hibiscus print bustier top",
   "brand": "",
   "category": "Top",
   "size": "XS",
   "color": "Green / pink print",
   "condition": "Very good",
   "photo": "jas2-hibiscus-top.jpg",
   "status": "sell",
   "rent_price_cents": null,
   "sale_price_cents": 2500,
   "purchase_price_cents": 5000
  },
  {
   "id": "j16",
   "name": "White crochet resort pants",
   "brand": "",
   "category": "Bottom",
   "size": "XS",
   "color": "White",
   "condition": "Very good",
   "photo": "jas2-crochet-pants.jpg",
   "status": "sell",
   "rent_price_cents": null,
   "sale_price_cents": 3500,
   "purchase_price_cents": 7000
  },
  {
   "id": "j17",
   "name": "Ivory corset tiered gown",
   "brand": "",
   "category": "Dress",
   "size": "XS",
   "color": "Ivory",
   "condition": "Excellent",
   "photo": "jas2-corset-gown.jpg",
   "status": "rent",
   "rent_price_cents": 5000,
   "sale_price_cents": null
  },
  {
   "id": "j18",
   "name": "Black lace-trim mini dress",
   "brand": "",
   "category": "Dress",
   "size": "XS",
   "color": "Black",
   "condition": "Very good",
   "photo": "jas2-lace-mini.jpg",
   "status": "rent",
   "rent_price_cents": 2500,
   "sale_price_cents": null
  }
 ]
};
